import os
from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
import tempfile
import uuid
import torch
from huggingface_hub import hf_hub_download

# Import the load_model function from the real modeling_airs.py
from modeling_airs import load_model

app = FastAPI(title="AIRS Sprint 1 - Respiratory Disease Classifier API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 1. Download and load the actual PyTorch model
# The token is read from the .env file or environment variables
HF_TOKEN = os.environ.get("HF_TOKEN")
REPO_ID = "Quantilytix/airs-sprint1-models"
# Using Exp4 because it naturally takes both tabular and raw waveform audio
MODEL_CONFIG = "exp4-encoder-free-unified/fold-0/config.json"
MODEL_WEIGHTS = "exp4-encoder-free-unified/fold-0/pytorch_model.bin"

print("Downloading model from Hugging Face (this may take a moment)...")
try:
    local_config = hf_hub_download(repo_id=REPO_ID, filename=MODEL_CONFIG, token=HF_TOKEN)
    local_weights = hf_hub_download(repo_id=REPO_ID, filename=MODEL_WEIGHTS, token=HF_TOKEN)
    
    # Load the actual PyTorch architecture
    model, config = load_model(local_config, local_weights, map_location="cpu")
    print(f"Successfully loaded {config['model_class']}!")
except Exception as e:
    print(f"Error loading model: {e}")
    model = None

@app.get("/")
def read_root():
    return {"message": "Welcome to the AIRS Respiratory Classification API"}

@app.post("/predict")
async def predict(
    audio: UploadFile = File(...),
    age: int = Form(default=0),
    gender: str = Form(default="unknown"),
    symptoms: str = Form(default="")
):
    """
    Endpoint to receive audio and tabular data for prediction.
    """
    if model is None:
        return {"error": "Model failed to load."}

    file_extension = audio.filename.split(".")[-1] if audio.filename else "wav"
    temp_filename = f"{uuid.uuid4()}.{file_extension}"
    
    with open(temp_filename, "wb") as f:
        f.write(await audio.read())
        
    try:
        # Load audio using standard wave module (since torchaudio requires external codecs on Windows)
        import wave
        import numpy as np
        
        with wave.open(temp_filename, 'rb') as f:
            sr = f.getframerate()
            frames = f.readframes(f.getnframes())
            # We assume 16-bit PCM WAV (like the one generated by our test script)
            waveform = torch.from_numpy(np.frombuffer(frames, dtype=np.int16)).float()
            # Normalize to [-1.0, 1.0]
            waveform = waveform / 32768.0
            
            # If stereo, convert to mono
            if f.getnchannels() > 1:
                waveform = waveform.view(-1, f.getnchannels())
                waveform = torch.mean(waveform, dim=1)
                
            waveform = waveform.unsqueeze(0) # add batch dimension: (1, T)
            
        # The model expects frame_len usually at 16kHz.
        # Since our test dummy and typical Web Audio is 16k-48k, we won't strictly resample here
        # unless necessary, but let's assume 16kHz for simplicity in this demo.
        cough_wav = waveform


        # Mock Tabular features. The model expects 9 features.
        # We will create a dummy 9-dimensional tensor based on the form inputs.
        # Feature 0: Age (normalized roughly)
        # Feature 1: Gender (0 for male, 1 for female)
        # Features 2-8: Symptoms/other metrics
        gender_feat = 1.0 if gender.lower() == "female" else 0.0
        symptom_count = float(len(symptoms.split(","))) if symptoms else 0.0
        
        tab_features = torch.tensor([[age / 100.0, gender_feat, symptom_count, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], dtype=torch.float32)

        # Forward pass!
        # Exp4: EncoderFreeUnifiedModel expects: forward(self, tab, cough_wav=None, ...)
        with torch.no_grad():
            logits = model(tab=tab_features, cough_wav=cough_wav)
            probs = torch.nn.functional.softmax(logits, dim=-1)
            # NUM_CLASSES = 3. Assume class 0: Healthy, 1: Disease A, 2: Disease B
            # We'll just take probability of not-healthy (sum of class 1 + 2)
            prob_disease = (probs[0, 1] + probs[0, 2]).item()

    except Exception as e:
        if os.path.exists(temp_filename):
            os.remove(temp_filename)
        return {"error": str(e)}

    # Clean up
    if os.path.exists(temp_filename):
        os.remove(temp_filename)
        
    return {
        "status": "success",
        "filename": audio.filename,
        "tabular_data": {"age": age, "gender": gender, "symptoms": symptoms},
        "prediction": {
            "disease_probability": prob_disease,
            "diagnosis": "Positive" if prob_disease > 0.5 else "Negative",
            "confidence": "High" if max(prob_disease, 1 - prob_disease) > 0.8 else "Medium",
            "model_version": config["model_class"]
        }
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
